version: "3.7"
services:
  mypostgres:
    image: postgres
    container_name: mypostgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Ahmadzai1$"
      POSTGRES_DB: "ticketing-app"
    ports:
      - "5435:5432"
    restart: always
    volumes:
      - initdb:/var/lib/postgresql/data
    networks:
      - webnet
  ticketing-app:
    build: .
    container_name: ticketingapp
    ports:
      - "8081:8081"
    networks:
      - webnet
    depends_on:
      - mypostgres
networks:
  webnet:
    driver: bridge
volumes:
  initdb:
